version: '3'
services:
  postgres:
    restart: "no"
    container_name: techguild-postgres
    image: "postgres:latest"
    ports:
      - "7777:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=secret

  redis:
    restart: "no"
    container_name: techguild-redis
    image: "redis:latest"
    ports:
      - "6379:6379"