spring:
  datasource:
    url: jdbc:postgresql://localhost:7777/database
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  cache:
    type: simple
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  data:
    rest:
      base-path: api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always

tech-guild:
  config:
    find-user-delay: 1s
